GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO g11origenet_g11origenet;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO g11origenet_g11origenet;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO g11origenet_g11origenet;